language: node_js
node_js:
  - 12 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "repuzzle-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: corndotpop
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: K7qDVPe4wLflk3ypw8sK5W0PtECq2EtX1bmUh+xSnw41+FYvgOaK+x0hCDYfUfiiMVQDCKQqmPFNCJ+QEen8YXm1qpXb31vKSsPzHdovQ0xtLQ+XZZxqmNYSVQWVa4EihkDGyfQBSMIXKCUdNOvpAKQCn+LdVNlzEdvFZBChsjaovh7CYFwAEfjFdoUbKq1TDOIppx2fNYFNkJbTtYYWrmm2wfFA8H7YO1CK8qKHRcI9ghCUqqwWrSQdiVx3ux+IyOd5ByrKeIJnAwI9IhXkgn8KKycfei2XndnbOJf0SIs2qDPYC8bx+w9sw9+lBwGifows4chP0I8AtnOEy4vxyxFgYAQri1YEthyaiZ0evQ/fDuL4QU83a2U1wtBW4hO/MexBF6N+1QvpkvVqHgvSqBm+CWTG8hw3iyRCoCYHb2DT6jAf1IKg7mjl6t7pGhaY+HBlyqF2en4r7lqeBCnru4LJMnv2ETQmyT5mA16yThpOxqvRfa4TH/eEM5PlQA2SxWqmzoTXkWnaYtG2PVpfIxUuLs3qIm/QBsVXRkL/cy+uqbWAkRW2ukJH2fPU+yMaQPeWFn/OrZRjCPPj+I6VRAMYTYwoFecr7xtT48G9ECHZh1mdpw0LTw82KhftgaPyQGk/43cqy2BoJhNVWqkmbxVEF4kvxFW/5szloR9K6UU=
